-- Create failed_webhooks table
CREATE TABLE IF NOT EXISTS "stampede_failed_webhook" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stampede_failed_webhook_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"raw_data" varchar(2048) NOT NULL,
	"error_message" varchar(1024) NOT NULL,
	"error_details" varchar(2048),
	"status" varchar(50) DEFAULT 'pending' NOT NULL,
	"extracted_name" varchar(256),
	"extracted_email" varchar(256),
	"extracted_phone" varchar(256),
	"extracted_transaction_id" varchar(256),
	"extracted_screenshot" varchar(256),
	"notes" varchar(1024),
	"created_at" timestamp DEFAULT now(),
	"resolved_at" timestamp
);

-- Create indexes
CREATE INDEX IF NOT EXISTS "status_idx" ON "stampede_failed_webhook" ("status");
CREATE INDEX IF NOT EXISTS "created_at_idx" ON "stampede_failed_webhook" ("created_at");